#!/bin/bash

if [ $# = 0 ]; then
	echo "Usage: `basename $0` [password]"
	exit
fi

password=$1
length=`expr length $password`
echo "Length: $length"
if [ $length -le "8" ]; then
	echo "Password should be at least 8 characters"; exit 0
elif [ ! `echo "$password" | grep -e [0-9]` ]; then
	echo "Password must contain at least one number"
elif [ ! `echo $password | grep [\@\#\$\%\\*\\+\-\=]` ]; then
	echo "Password must contain at least one special character (@#$%$*+-=)"; exit 0
else
	echo "Password is valid!"
fi
